package:
  name: prisms-jobs
  version: "4.0.2"

source:
  git_rev: v4.0.2
  git_url: https://github.com/prisms-center/prisms_jobs.git

requirements:
  build:
    - python
    - setuptools
    - future
    - six
    - argparse # [py26]
  run:
    - python
    - future
    - six
    - argparse # [py26]

about:
  home: https://prisms-center.github.io/prisms_jobs_docs/
  license: LGPL2.1+
  license_file: LICENSE
